name: Java CI with Maven github action examples

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Docker login and push
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build -t ${{ secrets.ALIYUN_REPOSITORY }} .
          docker push ${{ secrets.ALIYUN_REPOSITORY }}

  deploy:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@main
        with:
          host: ${{ secrets.ALIYUN_HOST }}
          username: ${{ secrets.ALIYUN_USER }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          script: |
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            docker stop $(docker ps --filter "ancestor=${{ secrets.ALIYUN_REPOSITORY }}" -q) || true
            docker rm -v $(docker ps --filter "ancestor=${{ secrets.ALIYUN_REPOSITORY }}" -q) || true
            docker rmi -f $(docker images "${{ secrets.ALIYUN_REPOSITORY }}" -q) || true
            docker pull ${{ secrets.ALIYUN_REPOSITORY }}
            docker run -p 8080:8080 -d ${{ secrets.ALIYUN_REPOSITORY }}
